# Generated by Django 2.2.5 on 2019-11-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAPIs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank_branches',
            name='id',
        ),
        migrations.AlterField(
            model_name='bank_branches',
            name='ifsc',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
