# Generated by Django 2.2.5 on 2019-11-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankAPIs', '0002_auto_20191111_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_branches',
            name='bank_id',
            field=models.CharField(max_length=100),
        ),
    ]
